// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5cy8yXieWAzUdq2Xqoc8Jh0NNmINVxPM',
    appId: '1:467064241116:web:4edcc803d6f70cfa99ad19',
    messagingSenderId: '467064241116',
    projectId: 'quiz-ba804',
    authDomain: 'quiz-ba804.firebaseapp.com',
    storageBucket: 'quiz-ba804.appspot.com',
    measurementId: 'G-PP5GJ2WGXE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlGrRJo6TwIHFRhCiHCJhXnF_Fv6PzSew',
    appId: '1:467064241116:android:f55f8605188adbc499ad19',
    messagingSenderId: '467064241116',
    projectId: 'quiz-ba804',
    storageBucket: 'quiz-ba804.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZ-c0k4UpIAnnh3m9iAEbH7YuOA1OTHik',
    appId: '1:467064241116:ios:f2b9a8be26fb134399ad19',
    messagingSenderId: '467064241116',
    projectId: 'quiz-ba804',
    storageBucket: 'quiz-ba804.appspot.com',
    iosBundleId: 'com.example.quiz',
  );
}
